### ISSUE TITLE
Util fails with Error connecting to SCD30: Conn(Nix(Sys(EINVAL)))

### ISSUE THREAD

**Issue by Codeleiche** [ryankurte/rust-sensor-scd30#5]
Hello, I just tried to use the scd30-util on my raspberry pi 4 to get an scd30 rust programming kick start but it fails with `Error connecting to SCD30: Conn(Nix(Sys(EINVAL)))`. I checked that I have permission on the i2c bus and can connect to the scd30 via python. Any idea on how to fix that? 
thx

**Comment by ryankurte** [comment]
howdy, is it definitely on [`/dev/i2c-1`](https://github.com/ryankurte/rust-sensor-scd30/blob/master/src/main.rs#L29)? you might need to pass the `--i2c` argument to select the correct bus.

**Comment by Codeleiche** [comment]
Yes, I solved the problem by using the issue by using the rppal crate for the i2c connection and changing all the `DEFAULT_ADDRESS << 1` in the base.rs file with `DEFAULT_ADDRESS << 1` it now works :)

**Comment by ryankurte** [comment]
thanks for the report! fixed in `v0.4.0`
